#spring.datasource.url=jdbc:h2:mem:practice_db
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.datasource.url=jdbc:postgresql://localhost:5432/dmk_db
spring.datasource.username=postgres
spring.datasource.password=pg12345
spring.jpa.hibernate.ddl-auto=update